export function htmlReportGenerator(report = {}) {
  const score = report.securityScoreReport ?? {};
  const executive = report.executiveReport ?? {};
  const dependency = report.dependencyRiskReport ?? {};
  const assessment = report.assessmentReport ?? {};
  const wallet = report.walletReport ?? {};
  const inventory = report.inventoryReport ?? {};

  const securityScore = score.securityScore ?? "N/A";
  const riskLevel = score.riskLevel ?? "UNKNOWN";
  const grade = score.grade ?? score.securityGrade ?? "N/A";
  const topPriority = score.topPriority ?? "Review high and critical findings.";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Quantum Shield Trinity Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background: #0f172a;
      color: #e5e7eb;
      margin: 0;
      padding: 32px;
    }
    .container {
      max-width: 1100px;
      margin: auto;
    }
    .header {
      padding: 28px;
      border-radius: 18px;
      background: linear-gradient(135deg, #1e293b, #111827);
      border: 1px solid #334155;
      margin-bottom: 24px;
    }
    h1 {
      margin: 0 0 8px;
      font-size: 34px;
    }
    .subtitle {
      color: #94a3b8;
      font-size: 16px;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 16px;
      margin-bottom: 24px;
    }
    .card {
      background: #111827;
      border: 1px solid #334155;
      border-radius: 16px;
      padding: 20px;
    }
    .label {
      color: #94a3b8;
      font-size: 13px;
      text-transform: uppercase;
      letter-spacing: .08em;
    }
    .value {
      font-size: 30px;
      font-weight: bold;
      margin-top: 8px;
    }
    .risk-low { color: #22c55e; }
    .risk-medium { color: #f59e0b; }
    .risk-high { color: #fb7185; }
    .risk-critical { color: #ef4444; }
    .section {
      background: #111827;
      border: 1px solid #334155;
      border-radius: 16px;
      padding: 22px;
      margin-bottom: 20px;
    }
    h2 {
      margin-top: 0;
      color: #f8fafc;
    }
    pre {
      white-space: pre-wrap;
      background: #020617;
      border: 1px solid #1e293b;
      border-radius: 12px;
      padding: 16px;
      overflow-x: auto;
      color: #cbd5e1;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 12px;
    }
    th, td {
      border-bottom: 1px solid #334155;
      padding: 10px;
      text-align: left;
      vertical-align: top;
    }
    th {
      color: #93c5fd;
    }
    .footer {
      color: #64748b;
      font-size: 13px;
      margin-top: 24px;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Quantum Shield Trinity</h1>
      <div class="subtitle">Executive security, quantum exposure, wallet, dependency, and migration risk report.</div>
    </div>

    <div class="grid">
      <div class="card">
        <div class="label">Security Score</div>
        <div class="value">${escapeHtml(securityScore)}/100</div>
      </div>
      <div class="card">
        <div class="label">Risk Level</div>
        <div class="value ${riskClass(riskLevel)}">${escapeHtml(riskLevel)}</div>
      </div>
      <div class="card">
        <div class="label">Grade</div>
        <div class="value">${escapeHtml(grade)}</div>
      </div>
      <div class="card">
        <div class="label">Version</div>
        <div class="value">${escapeHtml(report.version ?? "N/A")}</div>
      </div>
    </div>

    <div class="section">
      <h2>Top Priority</h2>
      <p>${escapeHtml(topPriority)}</p>
    </div>

    <div class="section">
      <h2>Executive Summary</h2>
      <pre>${escapeHtml(JSON.stringify(executive, null, 2))}</pre>
    </div>

    <div class="section">
      <h2>Dependency Risk</h2>
      ${renderDependencyTable(dependency)}
    </div>

    <div class="section">
      <h2>Security Assessment</h2>
      <pre>${escapeHtml(JSON.stringify(assessment, null, 2))}</pre>
    </div>

    <div class="section">
      <h2>Wallet Risk</h2>
      <pre>${escapeHtml(JSON.stringify(wallet, null, 2))}</pre>
    </div>

    <div class="section">
      <h2>Crypto Inventory</h2>
      <pre>${escapeHtml(JSON.stringify(inventory, null, 2))}</pre>
    </div>

    <div class="footer">
      Generated by Quantum Shield Trinity
    </div>
  </div>
</body>
</html>`;
}

function renderDependencyTable(dependency = {}) {
  const findings = dependency.findings ?? [];

  if (!findings.length) {
    return "<p>No dependency findings detected.</p>";
  }

  const rows = findings
    .map(
      finding => `<tr>
        <td>${escapeHtml(finding.dependency)}</td>
        <td>${escapeHtml(finding.version)}</td>
        <td>${escapeHtml(finding.severity)}</td>
        <td>${escapeHtml(finding.category)}</td>
        <td>${escapeHtml(finding.recommendation)}</td>
      </tr>`
    )
    .join("");

  return `<table>
    <thead>
      <tr>
        <th>Dependency</th>
        <th>Version</th>
        <th>Severity</th>
        <th>Category</th>
        <th>Recommendation</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>`;
}

function riskClass(riskLevel = "") {
  const normalized = String(riskLevel).toLowerCase();

  if (normalized === "low") return "risk-low";
  if (normalized === "medium") return "risk-medium";
  if (normalized === "high") return "risk-high";
  if (normalized === "critical") return "risk-critical";

  return "";
}

function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
