export function securityBadgeGenerator(report = {}) {
  const score = report.securityScoreReport ?? {};
  const quantum = report.quantumReadinessReport ?? {};
  const crypto = report.cryptoInventoryReport ?? report.inventoryReport ?? {};

  const securityScore = score.securityScore ?? 0;
  const grade = score.grade ?? score.securityGrade ?? "N/A";
  const riskLevel = score.riskLevel ?? "UNKNOWN";
  const quantumScore = quantum.quantumReadinessScore ?? "N/A";
  const quantumRisk = quantum.quantumRiskLevel ?? "UNKNOWN";
  const cryptoAssets = crypto.totalCryptoAssets ?? 0;

  const badgeData = {
    generator: "Quantum Shield Trinity Security Badge Generator",
    generatedAt: new Date().toISOString(),
    securityScore,
    grade,
    riskLevel,
    quantumReadinessScore: quantumScore,
    quantumRiskLevel: quantumRisk,
    cryptoAssets,
    status: getStatus(riskLevel),
    label: `Quantum Shield ${grade}`,
    message: `Score ${securityScore}/100 • Risk ${riskLevel}`
  };

  return {
    engine: "Security Badge Generator",
    scannerVersion: "1.0.0",
    outputFiles: {
      svg: "badge.svg",
      json: "badge.json",
      html: "badge.html"
    },
    badgeData,
    svg: buildSvgBadge(badgeData),
    html: buildHtmlBadge(badgeData)
  };
}

function getStatus(riskLevel = "") {
  const normalized = String(riskLevel).toUpperCase();

  if (normalized === "LOW") return "VERIFIED";
  if (normalized === "MEDIUM") return "REVIEW";
  if (normalized === "HIGH") return "HIGH RISK";
  if (normalized === "CRITICAL") return "CRITICAL";

  return "UNKNOWN";
}

function getColor(riskLevel = "") {
  const normalized = String(riskLevel).toUpperCase();

  if (normalized === "LOW") return "#22c55e";
  if (normalized === "MEDIUM") return "#f59e0b";
  if (normalized === "HIGH") return "#fb7185";
  if (normalized === "CRITICAL") return "#ef4444";

  return "#64748b";
}

function buildSvgBadge(data = {}) {
  const color = getColor(data.riskLevel);
  const label = escapeXml("Quantum Shield");
  const message = escapeXml(`${data.grade} • ${data.securityScore}/100 • ${data.riskLevel}`);

  return `<svg xmlns="http://www.w3.org/2000/svg" width="520" height="120" viewBox="0 0 520 120" role="img" aria-label="Quantum Shield Trinity Security Badge">
  <rect width="520" height="120" rx="18" fill="#0f172a"/>
  <rect x="1" y="1" width="518" height="118" rx="18" fill="none" stroke="#334155" stroke-width="2"/>
  <text x="28" y="38" fill="#e5e7eb" font-family="Arial, sans-serif" font-size="22" font-weight="700">${label}</text>
  <text x="28" y="70" fill="#94a3b8" font-family="Arial, sans-serif" font-size="15">Security Intelligence Badge</text>
  <rect x="300" y="24" width="190" height="44" rx="12" fill="${color}"/>
  <text x="395" y="53" text-anchor="middle" fill="#ffffff" font-family="Arial, sans-serif" font-size="18" font-weight="700">${message}</text>
  <text x="28" y="98" fill="#93c5fd" font-family="Arial, sans-serif" font-size="14">Quantum Ready: ${escapeXml(data.quantumReadinessScore)}/100 • Crypto Assets: ${escapeXml(data.cryptoAssets)}</text>
</svg>`;
}

function buildHtmlBadge(data = {}) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Quantum Shield Trinity Security Badge</title>
  <style>
    body {
      margin: 0;
      padding: 32px;
      background: #0f172a;
      font-family: Arial, sans-serif;
      color: #e5e7eb;
    }
    .badge {
      max-width: 560px;
      border: 1px solid #334155;
      border-radius: 18px;
      padding: 24px;
      background: #111827;
    }
    .title {
      font-size: 26px;
      font-weight: 700;
      margin-bottom: 8px;
    }
    .status {
      display: inline-block;
      margin-top: 14px;
      padding: 10px 14px;
      border-radius: 999px;
      background: ${getColor(data.riskLevel)};
      color: #ffffff;
      font-weight: 700;
    }
    .metric {
      margin-top: 12px;
      color: #cbd5e1;
    }
    .small {
      margin-top: 18px;
      color: #94a3b8;
      font-size: 13px;
    }
  </style>
</head>
<body>
  <div class="badge">
    <div class="title">Quantum Shield Trinity</div>
    <div>Security Intelligence Badge</div>

    <div class="status">${escapeHtml(data.status)}</div>

    <div class="metric">Security Score: ${escapeHtml(data.securityScore)}/100</div>
    <div class="metric">Grade: ${escapeHtml(data.grade)}</div>
    <div class="metric">Risk Level: ${escapeHtml(data.riskLevel)}</div>
    <div class="metric">Quantum Readiness: ${escapeHtml(data.quantumReadinessScore)}/100</div>
    <div class="metric">Quantum Risk: ${escapeHtml(data.quantumRiskLevel)}</div>
    <div class="metric">Crypto Assets Detected: ${escapeHtml(data.cryptoAssets)}</div>

    <div class="small">Generated by Quantum Shield Trinity</div>
  </div>
</body>
</html>`;
}

function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function escapeXml(value = "") {
  return escapeHtml(value);
}
